name: Deploy Crates

on:
  - push
  - pull_request

jobs:
  deploy-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Dry run
        run: cargo publish --workspace --dry-run

      - name: Login to crates.io
        run: cargo login $TOKEN
        if: github.ref == 'refs/heads/master'
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --workspace
        if: github.ref == 'refs/heads/master'
